In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Plant_Parameters.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25,random_state= 0)

In [5]:
print(X_train)

[[ 6.61717569  0.42800936 15.48571785 ... 23.50794506 73.94517959
  50.23901061]
 [ 5.74666107  0.26322593 28.50492466 ... 33.1689394  73.82514768
  78.34881358]
 [ 6.47666055  0.41645736 15.90568379 ... 22.87891646 78.38523164
  70.27881671]
 ...
 [ 5.54621167  0.85150998 20.82597872 ... 39.80452494 64.04249582
  84.53556063]
 [ 6.21027537  1.0925606  37.91191252 ... 39.4611254  68.22939893
  70.36206651]
 [ 5.97752148  0.53735999 10.27954915 ... 25.52219306 77.52955221
  66.08923181]]


In [6]:
print(y_train)

['Carrots' 'Rice' 'Carrots' ... 'Eggplant' 'Eggplant' 'Strawberries']


In [7]:
print(X_test)

[[ 6.0079384   0.20406    13.97153796 ... 21.67582638 70.93370353
  69.13277668]
 [ 6.32605311  0.66377913 13.27437868 ... 23.06283705 79.64218079
  66.57544555]
 [ 5.99666363  0.33245715 23.78540073 ... 28.0182059  79.30027725
  81.85132057]
 ...
 [ 6.20569491  1.92961042 28.05618246 ... 47.01638078 70.09673022
  77.30697856]
 [ 6.07628302  0.21989782 20.1538831  ... 38.31630956 67.1700534
  57.90583914]
 [ 6.71439508  0.82523946 29.28276393 ... 35.08687938 66.72371874
  77.19481959]]


In [8]:
print(y_test)

['Carrots' 'Strawberries' 'Rice' ... 'Tomato' 'Corn' 'Chili']


In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [53]:
print(X_train)

[[ 0.08366582  1.02526354  0.29600528 ... -1.1158681  -0.95305632
   0.80024769]
 [ 0.80497522 -0.5474519   0.41511197 ... -0.10858964 -0.78456759
   0.2750721 ]
 [ 1.57880213  0.12103373  1.25793015 ... -0.68252425 -0.25318088
   0.78982754]
 ...
 [-1.80449389  0.33587875 -0.30250088 ...  1.48691244 -0.57105181
   1.34120928]
 [-0.24033442  0.90800064  1.64662316 ...  1.43480642 -0.03635615
  -0.2440798 ]
 [-0.78857129 -0.40974095 -1.50561332 ... -0.68022911  1.15133591
  -0.72199147]]


In [10]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [11]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Carrots' 'Carrots']
 ['Strawberries' 'Strawberries']
 ['Rice' 'Rice']
 ...
 ['Tomato' 'Tomato']
 ['Corn' 'Corn']
 ['Chili' 'Chili']]


In [12]:
print(classifier.predict(sc.transform([[5.761144646,0.750072789,17.40051971,137.5378463,21.40644822,19.86246667,22.00249276,70.98998425,70.56735688
]])))

['Strawberries']


In [13]:
print(classifier.predict(sc.transform([[5.88286223,0.393125882,30.92046619,134.6942429,48.03089229,39.71911966,35.13391183,68.84002917,80.33718029
]])))

['Corn']


In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2374    0    0    0    0    0  107    0    0    0]
 [   0 1863    0    8  638    0    0    6    6    0]
 [   0    0 2448    0    0    0    0    0    0    0]
 [   2   60    0 1702   26   22    0  666    0    3]
 [   0  818    0    1 1709    0    0    2    0    0]
 [   0    0    0    5    0 2490    0    3    0    0]
 [  44    0    0    0    0    0 2522    0    0    0]
 [   0   79    0  454   26   21    0 1891    0    0]
 [   0   22    0    1    5    0    0    0 2467    0]
 [   0    0    0    0    0    0    0    0    0 2509]]


0.879

In [15]:
y_train_pred = classifier.predict(X_train)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Carrots' 'Carrots']
 ['Strawberries' 'Strawberries']
 ['Rice' 'Rice']
 ...
 ['Tomato' 'Tomato']
 ['Corn' 'Corn']
 ['Chili' 'Chili']]


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_train,y_train_pred)

[[2374    0    0    0    0    0  107    0    0    0]
 [   0 1863    0    8  638    0    0    6    6    0]
 [   0    0 2448    0    0    0    0    0    0    0]
 [   2   60    0 1702   26   22    0  666    0    3]
 [   0  818    0    1 1709    0    0    2    0    0]
 [   0    0    0    5    0 2490    0    3    0    0]
 [  44    0    0    0    0    0 2522    0    0    0]
 [   0   79    0  454   26   21    0 1891    0    0]
 [   0   22    0    1    5    0    0    0 2467    0]
 [   0    0    0    0    0    0    0    0    0 2509]]


0.9213066666666667